### PR TITLE
Install missing Python package

### PR DESCRIPTION
**Pull request by antoyo**
[My CI was failing due to a missing python3 executable.](https://github.com/antoyo/jekyll-antoyo-blog/actions/runs/3614291998/jobs/6090624986#step:7:529)

This fixes the issue.

### CODE REVIEW

**Comment by jeffreytse** [comment]
Hi @antoyo 

Thanks for your contribution. This project has provided an option called [pre_build_commands](https://github.com/jeffreytse/jekyll-deploy-action#-usage) to add extra packages.

```yml
# Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@v0.4.0
        with:
            ...
            pre_build_commands: 'pacman -S --noconfirm python'        # Add extra packages for your deployment
```

Thanks & Regards

**Review by jeffreytse — COMMENTED** [review]
Hi @antoyo 

Thanks for your contribution. This project has provided an option called [pre_build_commands](https://github.com/jeffreytse/jekyll-deploy-action#-usage) to add extra packages.

```yml
# Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@v0.4.0
        with:
            ...
            pre_build_commands: 'pacman -S --noconfirm python'        # Add extra packages for your deployment
```

Thanks & Regards

**Comment by antoyo** [comment]
Oh, sorry, I should have been clearer.
It seems that `jekyll-deploy-action` now required the `python` package, possibly due to an update to `pygments.rb`.

**Comment by jeffreytse** [comment]
Hi @antoyo 

I think that's because you are using the `pygments` in your projects, just simply adding the `pre_build_commands` can settle your issue. : )

Thanks & Regards

**Comment by antoyo** [comment]
Alright. If you prefer to not always install packages that are needed for optional dependencies, please close this PR.

**Comment by jeffreytse** [comment]
Hi, as other people may not need the python environment, for time saving, we need to reduce all steps which are unnecessary.

**Pull request closed without merging**
